### ISSUE TITLE
rename repository?

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-mail#1]
1.: great extension, will check it out
2.: in the old days when we discussed naming patterns for community extensions we agreed that we want to name the extensions based on the used technology, not on concepts or domains. Thats why camunda-bpm-assert is not camunda-bpm-test and camunda-bpm-reactor is not camunda-bpm-eventbus. It allows us to have several extensions for the same domain using diffenerent technologies. No "mail " covers the email domain, but according to the pattern, "camunda-bpm-greenmail" woud have been the better name. WDYT?

**Comment by saig0** [comment]
Hi Jan,

thank you for your feedback and congratulation to the first issue :+1: 

This extension is based on javamail (aka mail). Greenmail is only a mock mailserver which is used for unit tests. So I think camunda-bpm-mail is ok. What do you think?

Best regards,
Philipp

**Comment by jangalinski** [comment]
Ah, ok, sorry I got that wrong. mail it is.
