### ISSUE TITLE
Why a camunda-engine dependency?

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda-bpm-mail#2]
The connector has a (provided) dependency to `camunda-engine`. Is this required for anything else than throwing a `ProcessEngineException` [here](https://github.com/camunda/camunda-bpm-mail/blob/1.0.0/extension/core/src/main/java/org/camunda/bpm/extension/mail/send/SendMailConnector.java#L65)? If not, I propose to remove the dependency and throw a connector-specific exception (e.g. `MailConnectorException`). I find that cleaner and the setup gets simpler (see for example https://forum.camunda.org/t/problems-using-camunda-bpm-mail-connectors/1359).

**Comment by saig0** [comment]
The dependency is used for the exceptions and tests. I agree with you and will change the scope of the dependecy to _test_.
