### ISSUE TITLE
Poll connector marks all emails as read

### ISSUE THREAD

**Issue by dalewking** [camunda/camunda-bpm-mail#20]
Still investigating why this happens but after using poll on gmail all the emails in the folder end up marked as read. I have existing JavaMail code that I am trying to replace with camunda process engine and the existing code does not have this problem so there must be something special you are doing.

**Comment by dalewking** [comment]
After some googling, discovered that this can be controlled by using the mail.imaps.peek property which can be done in the mail-config.properties. Setting that mail.imaps.peek=true will prevent it from being marked as read.

**Comment by dalewking** [comment]
Reopening because this should probably be addressed in the documentation somewhere, for example by adding it as a commented out property with comments explaining it.

**Comment by saig0** [comment]
:+1: I added it to the documentation.
