### ISSUE TITLE
Empty ${mail.getText()} in subprocesses - pizza example

### ISSUE THREAD

**Issue by blackcoffee4u** [camunda/camunda-bpm-mail#37]
Hi everybody,
I tried to get the pizza example work with my mail-accounts.
I managed to poll the mails from my account and for each mail a new "Make pizza" process is created.
So far so good.
Unfortunately the mail variable is not passed / available in the subprocess. 
As result the "order"-variable is empty and the confirmation mail doesn't fire becaus of missing mailadress and ${mail.getText()}.
I would be thankfull if anybody could point my nose to the right spot.

Kind regards

ps: I'm runnnig the example with the 7.14 tomcat server out of the download section / java 10

**Comment by saig0** [comment]
Hi @blackcoffee4u,

were you able to solve the issue?
What was the problem?
