### ISSUE TITLE
Send Mail and wait for response

### ISSUE THREAD

**Issue by aminmc** [camunda/camunda-bpm-mail#8]
Hello,

Is it possible to send an email within the BPMN and then have a service task that polls for the reply to the original email?  Is there a mechanism to correlate the email to the process that has already started?

Thanks

**Comment by saig0** [comment]
Hi @aminmc ,

currently there is no built-in mechanism for the correlation. If you poll emails with the task then you receive all emails. Using this basic tasks, you can built a correlation by your own using a kind of correlation key inside the email.

However, if you have an idea for a general implementation, I looking forwand to your approach.

**Comment by aminmc** [comment]
@saig0 thanks for your reply. I'll take a look and get back to you.  Do you want me to close this issue or leave it open?

**Comment by saig0** [comment]
@aminmc , I close this issue for now. Feel free to comment or re-open it when you have some new =)
